% scirpt for extracting synapse weight
%3by3 수동검증 코드,  nonclock, clock 차이 없음

 weight_table=[out.w1_1 out.w2_1 out.w3_1 out.w4_1 out.w5_1 out.w6_1 out.w7_1 out.w8_1 out.w9_1  ...
               out.w1_2 out.w2_2 out.w3_2 out.w4_2 out.w5_2 out.w6_2 out.w7_2 out.w8_2 out.w9_2  ...
               out.w1_3 out.w2_3 out.w3_3 out.w4_3 out.w5_3 out.w6_3 out.w7_3 out.w8_3 out.w9_3  ...
               out.w1_4 out.w2_4 out.w3_4 out.w4_4 out.w5_4 out.w6_4 out.w7_4 out.w8_4 out.w9_4 ];   
           
[wrow, wcol]=size(weight_table);
time_table= out.tout(:,1);

% synapse_var=struct('time',[ ],'weight',[ ],'last',0); %for synapse struct
% last_table=zeros(1,36);%for synapse map
% weight_table0=zeros(1,36);
% weight_table1=zeros(1,36);
% weight_table2=zeros(1,36);
% weight_table3=zeros(1,36);
% weight_table4=zeros(1,36);
% weight_table5=zeros(1,36);
% weight_table6=zeros(1,36);
% weight_table7=zeros(1,36);
% weight_table8=zeros(1,36);
% weight_table9=zeros(1,36);

for k =1:36

%making synapse struct
synapse_var(k).time=time_table(:,1);
synapse_var(k).weight=weight_table(:,k);
synapse_var(k).last= weight_table(wrow,k);
last_table(1,k)= synapse_var(k).last;
weight_table0(1,k)=weight_table(1,k);
weight_table1(1,k)=weight_table(40001,k);
weight_table2(1,k)=weight_table(80001,k);
weight_table3(1,k)=weight_table(120001,k);
weight_table4(1,k)=weight_table(160001,k);
weight_table5(1,k)=weight_table(200001,k);
weight_table6(1,k)=weight_table(240001,k);
weight_table7(1,k)=weight_table(280001,k);
weight_table8(1,k)=weight_table(320001,k);
weight_table9(1,k)=weight_table(360001,k);
end
%원본 지우지 마셈

fixedStepSize = 0.005;
samplingInterval = 0.400 / fixedStepSize; % 이 두개를 조정하면된다 // 2초기준 
% fixed x sample 곱하면 0.002나오면 됨

for k =1:36

%making synapse struct
synapse_var(k).time=time_table(:,1);
synapse_var(k).weight=weight_table(:,k);
synapse_var(k).last= weight_table(wrow,k);
last_table(1,k)= synapse_var(k).last;
weight_table0(1,k)=weight_table(1,k);
weight_table1(1,k)=weight_table(2 * samplingInterval + 1,k);
weight_table2(1,k)=weight_table(4 * samplingInterval + 1,k);
weight_table3(1,k)=weight_table(6 * samplingInterval + 1,k);
weight_table4(1,k)=weight_table(8 * samplingInterval + 1,k);
weight_table5(1,k)=weight_table(10 * samplingInterval + 1,k);
weight_table6(1,k)=weight_table(12 * samplingInterval + 1,k);
weight_table7(1,k)=weight_table(14 * samplingInterval + 1,k);
weight_table8(1,k)=weight_table(16 * samplingInterval + 1,k);
weight_table9(1,k)=weight_table(18 * samplingInterval + 1,k);
end

% Desired width and height for the figure
width = 1000;
height = 800;

% Get the screen size
screenSize = get(0, 'ScreenSize');

% Calculate left and bottom positions to center the figure on the screen
left = (screenSize(3) - width) / 2;
bottom = (screenSize(4) - height) / 2;

% Create the figure with the specified position
figure('Position', [left, bottom, width, height]);

%making synapse map
synapse_map=[ weight_table0(1:9)' ...
              weight_table0(10:18)' ...
              weight_table0(19:27)' ...
              weight_table0(28:36)' ...
              weight_table1(1:9)' ...
              weight_table1(10:18)' ...
              weight_table1(19:27)' ...
              weight_table1(28:36)' ...
              weight_table2(1:9)' ...
              weight_table2(10:18)' ...
              weight_table2(19:27)' ...
              weight_table2(28:36)' ...
              weight_table3(1:9)' ...
              weight_table3(10:18)' ...
              weight_table3(19:27)' ...
              weight_table3(28:36)' ...
              weight_table4(1:9)' ...
              weight_table4(10:18)' ...
              weight_table4(19:27)' ...
              weight_table4(28:36)' ...
              weight_table5(1:9)' ...
              weight_table5(10:18)' ...
              weight_table5(19:27)' ...
              weight_table5(28:36)' ...
              weight_table6(1:9)' ...
              weight_table6(10:18)' ...
              weight_table6(19:27)' ...
              weight_table6(28:36)' ...
              weight_table7(1:9)' ...
              weight_table7(10:18)' ...
              weight_table7(19:27)' ...
              weight_table7(28:36)' ...
              weight_table8(1:9)' ...
              weight_table8(10:18)' ...
              weight_table8(19:27)' ...
              weight_table8(28:36)' ...
              weight_table9(1:9)' ...
              weight_table9(10:18)' ...
              weight_table9(19:27)' ...
              weight_table9(28:36)' ...
              last_table(1:9)' ...
              last_table(10:18)' ...
              last_table(19:27)' ...
              last_table(28:36)' ...
             ];
        
colormap(flipud(gray));
clim([0 150]);

for k= 1:44
subplot(11,4, k);
imagesc(reshape(synapse_map(:, k), 3, 3)')
hold on;
    % 빨간 숫자 표시 부분을 제거했습니다
end

%패턴 1개씩학습
writematrix(last_table,'synapes_weight_v1.csv')
%패턴 10개씩학습
%writematrix(last_table,'synapes_weight_v2.csv')
%패턴 50개씩학습
%writematrix(last_table,'synapes_weight_v3.csv')
%패턴 100개씩학습
%writematrix(last_table,'synapes_weight_v4.csv')